name: 'Get & Cache Dependencies'
description: 'to simpler the on github action workflow'
inputs:
  cache:
    description: 'wheather the cache is required or not.'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: inputs.cache == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.cache != 'true'
      run: npm ci
      shell: bash
